id: I6F0C83B4
ocr_import_info:
  timestamp: '2023-09-29T16:05:27.404019+00:00'
  batch_id: batch-f56c
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-30 00:09:38.280674+00:00
last_modified: 2023-09-30 00:09:38.280679+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG10854
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG10854
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཐུབ་བསྟན་ཆོས་ཀྱི་གྲགས་པ། ༼སྡེ་དགེ་པར་མ།༽
  languages:
  - bo
  author: དྷཱརྨ་ཀིརྟི་ཀུན་བཟང་བསོད་ནམས།
statistics:
  ocr_word_mean_confidence_index: 0.9601502612224108
  ocr_word_median_confidence_index: 0.99787045
bases:
  I1KG10888:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10888
      total_pages: 538
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG10888.txt
    statistics:
      ocr_word_median_confidence_index: 0.9946310650000001
      ocr_word_mean_confidence_index: 0.9490774705034023
  I1KG10889:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10889
      total_pages: 918
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG10889.txt
    statistics:
      ocr_word_median_confidence_index: 0.99888164
      ocr_word_mean_confidence_index: 0.9674303527122808
  I1KG10887:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10887
      total_pages: 278
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10887.txt
    statistics:
      ocr_word_median_confidence_index: 0.99782215
      ocr_word_mean_confidence_index: 0.9583735970338236
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
